### ISSUE TITLE
GPS Precision

### ISSUE THREAD

**Issue by juhavlintula** [juhavlintula/DamScan#2]
Using different sources for GPS data can generate rounding errors and unnecessary mismatches.

**Comment by WilfriedBl** [comment]
I'm not sure if "using different sources" is really the cause, since the original picture and the source of coordinates were always the same. Somehow the "same" coordinates became different either by copying the picture or importing/synchronizing it again into Daminion at a later point in time.

**Comment by WilfriedBl** [comment]
Even after very few days, I found many differences caused by rounding errors with the GPS data. In fact out of 1,196 new pictures from early October 2017, more than 50% (637) showed differences in a temporary catalog created on October, 11.  Reducing the precision of the GPS-values from 8 stepwise down to 0, the number of differences decreases (558, 26, 2, 2, 0). In all cases the representation in Daminion (Nxx° yy' zz,zz", Exx° yy' zz,zz", aaa.aa m) did not show any differences, except for the last 3 pictures (using 2 digits decimal precision), which had a different altitude of 1 resp 2 cm(!).
After initially writing the GPS data into the meta data using GeoSetter, I did not touch those later. However, I did change many other tags (categories, keywords ..) which were than synchronized by Daminion. Also synchronization did not write correctly categories/keywords for 3 images.

**Comment by WilfriedBl** [comment]
I was able to verify, when an image with GPS tags is imported into Daminion, some other tags being changed (not touching the GPS) and the meta data synchronized, the latitude/longitude values will be different.  However, this cannot be consistently reproduced and seems only to happen, when the Sync process needs to update many images.  For example, I was not able to reproduce it by importing only 4 images, but after importing and updating ~250 images, I saw differences for all of them.  Subsequently updating tags for 114 of the same images, GPS tag inconsistencies appeared for only 8 of those.
Instead of comparing all digits of the floating point values for latitude and longitude , I suggest to calculate the distance in meters and report the difference in DamCompare.py only if the distance is shorter than a certain threshold . Today I suggested code changes in DamImage.py to achieve this with a threshold of 1 m hard coded.  
Besides reducing the number of fault reports for GPS mismatches, additional information will be shown, e.g. "GPS, 4.919.... m distance, 256.0 m elev. difference"

**Comment by juhavlintula** [comment]
Merged your code into the my source. I did some slight changes, added the command line/INI-file options and incorporated the functionality both into DamScan and DamCompare.

PS. There was a small bug in your code, your distance was in 1000 kilometers, not in meters. :)
